services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tastetrack-backend
    ports:
      - "5000:5000"
    # ADD THIS ENVIRONMENT BLOCK:
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@tastetrack-mongo:27017/tastetrack?authSource=admin
      - JWT_SECRET=HilcoeProjectSecretKey
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tastetrack-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: tastetrack-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
  uploads: